### ISSUE TITLE
Unable to pin version

### ISSUE THREAD

**Issue by jabbera** [linuxserver/docker-unifi#1]
Wifi is pretty much the underpinning of my network access. Most containers I'm okay with auto-updating when the container cycles. This one, not so much. Unifi hasn't produced the most reliable updates which is part of my hesitation. It would be great if we could get a version pinning feature similarly to what was done with the Plex container so upgrades were not automatic.

Thanks!
Mike

**Comment by nhattan123** [comment]
Thank

**Comment by lonix** [comment]
jabbera, thanks for your feedback, we shall investigate this.

**Comment by sparklyballs** [comment]
we have that already....

set the variable ADVANCED_DISABLEUPDATES to anything other than unset, if that makes sense.
The container will then not update on startup.
Image refreshes will still get the latest version available, but you have to opt in manually to do those anyways.

**Comment by jabbera** [comment]
That's great! Thanks for the quick feedback.
