### ISSUE TITLE
Unifi 5.3.8

### ISSUE THREAD

**Issue by kmlucy** [linuxserver/docker-unifi#14]
To update to Unifi 5.3.8, the repository needs to be changed. See: https://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-5-3-8-Stable-Candidate-has-been-released/ba-p/1749831

**Comment by sparklyballs** [comment]
or just wait till monday when it's actually released to the current repo.
as per the release notice.

https://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-5-3-8-Stable-has-been-released/ba-p/1755779
 
"It will be posted to our downloads page and pushed to the repo on 12.12.16."

**Comment by kmlucy** [comment]
Ah, sorry, didn't see that. My bad.

**Comment by kmlucy** [comment]
@sparklyballs Can you bump to trigger a build?

**Comment by sparklyballs** [comment]
no, lol.

W: GPG error: http://dl.ubnt.com/unifi/debian unifi5 Release: The following signatures were invalid: BADSIG 06E85760C0A52C50 UniFi Developers <unifi-dev@ubnt.com>
W: The repository 'http://www.ubnt.com/downloads/unifi/debian unifi5 Release' is not signed.
Reading package lists...

their repo is still fackered, tried it earlier today, and just tried it again.
