### ISSUE TITLE
Update to 5.4.x LTS for the controller software?

### ISSUE THREAD

**Issue by idlethread** [linuxserver/docker-unifi#17]
Hi,

Unifi controller software will maintain a long term supported [release](https://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-LTS-announcement-release-schedule-update/ba-p/1803321) on 5.4.x (latest being 5.4.9).

Any change of getting the docker image updated?

Regards,
Amit

**Comment by sparklyballs** [comment]
it is up to date

the 5.x versions are temporarily pulled by unifi.

scroll to the bottom of this [link](https://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-5-4-9-Stable-has-been-released/ba-p/1800599)

**Comment by idlethread** [comment]
Indeed, thanks for the prompt reply.

**Comment by idlethread** [comment]
There is now a 5.4.14 available[1]. Any idea when the container will be upgraded to include it?

[1] https://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-5-4-14-Stable-has-been-released/ba-p/1890625

**Comment by j0nnymoe** [comment]
@idlethread this version will get picked up on the weekly image refresh which happens every friday at 11pm GMT.
