### ISSUE TITLE
Incorporate Letsencrypt certificate (with auto update)

### ISSUE THREAD

**Issue by marcus-no** [linuxserver/docker-unifi#2]
Would be wonderful if this (and others) container would incorporate letsencrypt auto-updating certs, or an easy way to use your own certs through a mapped volume

**Comment by zaggash** [comment]
I created à script I use to generate cert with letsencrypt on my haproxy container.
I can give the script if you need it.
Maybe a PR soon

**Comment by ktiedt** [comment]
@zaggash but is this unifi container accepting those certs too? I just switched from a different unifi container to this one and for the life of me, it will not accept my LE certs anymore...
