### ISSUE TITLE
What is the right way to upgrade to a newer version?

### ISSUE THREAD

**Issue by eric** [linuxserver/docker-unifi#21]
When a new version of the unifi controller comes out, what is the best way to upgrade to it? I didn't find anything in the docs to that talks about it.

**Comment by CHBMB** [comment]
Update the docker container

**Comment by eric** [comment]
Is there a way to specify a version of the controller?

**Comment by CHBMB** [comment]
No, we update the image every friday to the latest version in their PPA.
