### ISSUE TITLE
Add --smallfiles for mongod

### ISSUE THREAD

**Issue by ToeiRei** [linuxserver/docker-unifi#22]
From the mongod manuals:

> --smallfiles
> Sets MongoDB to use a smaller default file size. The --smallfiles option reduces the initial size for data files and limits the maximum size to 512 megabytes. --smallfiles also reduces the size of each journal file from 1 gigabyte to 128 megabytes. Use --smallfiles if you have a large number of databases that each holds a small quantity of data.
> 
> The --smallfiles option can lead the mongod instance to create a large number of files, which can affect performance for larger databases.

I would suggest that for smaller installations to reduce the footprint of the docker image

**Comment by paspo** [comment]
You can edit `data/system.properties` (it's in config directory) and add this line:
```
unifi.db.extraargs=--smallfiles
```
Restart the container and it's done.

**Comment by sparklyballs** [comment]
@paspo thanks for that tip

closing this now
