### ISSUE TITLE
Optional external mongodb

### ISSUE THREAD

**Issue by jkaberg** [linuxserver/docker-unifi#29]
Please add an option to let users use external MongoDB instead of built in.

https://community.ubnt.com/t5/UniFi-Wireless/External-MongoDB-Server/td-p/1305297

This will reduce size and overhead of the docker image when running an "central" mongodb shared by many applications.

**Comment by tobbenb** [comment]
If the solution is to edit the system.properties file, you can do this yourself as it's in the config mount and will survive updates.

**Comment by jkaberg** [comment]
@tobbenb The container will still run mongodb.

**Comment by sparklyballs** [comment]
unifi will not install without mongodb so it isn't a viable option
