### ISSUE TITLE
STUN service on port 3478 requires UDP not TCP

### ISSUE THREAD

**Issue by thehomerepot** [linuxserver/docker-unifi#34]
With the current steps to create a docker image, the STUN service will still have issues connecting to port 3478. This is because it uses UDP instead of TCP. Can you update the usage example to reflect that?

Non-Working Line
  -p 3478:3478 \

Working Line
  -p 3478:3478/udp \

**Comment by aptalca** [comment]
Heh, nice catch. I'll fix it

**Comment by dam09fr** [comment]
Thant you for the fix, I was using network bridge because I didnt find the origin of the problem !
