### ISSUE TITLE
Utilize UDP port 10001 for device discovery

### ISSUE THREAD

**Issue by nbadal** [linuxserver/docker-unifi#36]
It may be helpful to include UDP port 10001 in the example command, as listening on this port allows automatic device discovery (i.e. removes the need to manually set the inform address on devices).
 
Simply adding -p 10001:10001/udp enables this :)

https://help.ubnt.com/hc/en-us/articles/218506997-UniFi-Ports-Used

**Comment by aptalca** [comment]
Man, they keep changing the documentation. Thanks for the report
