### ISSUE TITLE
s6-applyuidgid: fatal: unable to exec java when etc folder is chmodded

### ISSUE THREAD

**Issue by zyphlar** [linuxserver/docker-unifi#42]
When writing docker files based on this image, and continuing the `/root/etc` style of copying necessary files and folders into the new image, it's easy for a stray chmod to make the /etc folder `drwxrwx---` (770) and owned by `root:root` which means that neither the `abc` user nor anyone except root will be able to run java -- which runs from the /etc/alternatives folder. The fix is to ensure the read and execute bits are set on /root and /root/etc so that the abc user is able to traverse and read stuff in that folder.

I'm not sure if there's a fix on your side for this other than being aware of the issue, since the problem is more likely to happen to anyone extending your image than to this image directly, but it took enough time for me to debug that I wanted to get the error message, `s6-applyuidgid: fatal: unable to exec java: Permission denied`, into search engines to save future users of this image some time. At most, if you want, maybe a bit in the README about considerations for extending this image could help. (The worst part is, chmods/chowns aren't really reflected in Git commits, so my initial troubleshooting techniques all failed.)

Feel free to close if adding considerations for extending into the README isn't something you care to do.

**Comment by sparklyballs** [comment]
we build our images and test them  before release so we find any issues with folders/files that need permission changes etc

there's no hard and fast rule with some apps being perfectly happy with no additional perms and others baulking like you have found 

we're not likely to add things to the README on the offchance someone is going to build an image based on ours logic is that if they're confident enough to build their own they can solve the issues that may arise etc
