### ISSUE TITLE
AP stuck in adopting phase after a container restart

### ISSUE THREAD

**Issue by EugenMayer** [linuxserver/docker-unifi#43]
I am running several linuxserver and a gazzilion other docker images, so docker should not be the actual issue.

Logs seem fine, just starting up as expected. Initially i adopted my AP and first a little message about stun not available popped up but then disappeared again.
Without restarting the actual docker-container now, everything works just fine. Unless i restart it, then the API stays in the adopting phase, never adopting .. as if the Controller has not proper key or what so ever. After some time the API is shown as disconnected, when i click on it, it starts adopting again.

I exposed all ports:
![image](https://user-images.githubusercontent.com/136934/35236776-c8ed55da-ffa8-11e7-882b-f9cdd6de2f43.png)

And i am using a host-volume mount for the `/config` partition:
![image](https://user-images.githubusercontent.com/136934/35236791-d99cc726-ffa8-11e7-8301-4a4a4acd2fba.png)

I am running the latest image version

Which is used, as i can see on the host. Using the controller on my mac worked just fine, so i expect a state issue in the docker-image...

But well obviously i am not the only one using this image and others would have complained too. Looked at https://help.ubnt.com/hc/en-us/articles/204950304-UniFi-UAP-stuck-in-adopting-state but did not find anything particular helpful.

Since now --host network is used is ask myself how sensitive the controller is the the broadcast not working ( if it is used ) ?

what i have done to diagnose:

1. ping from AP to my synology NAS which is running the docker container:
that one works, interestingly i cannot telnet to any port, not even 8443

2. `curl -L -k https://10.10.10.10:8443` worked from the AP

3. my networks router is an `opnsense` appliance, the AP / nas have both static leases and did not change their API during the "pairing"

**Comment by rogierlommers** [comment]
Did you try to set the inform url?

**Comment by EugenMayer** [comment]
After starting the container and using the `mca-cli` running 
`set-inform http://10.10.10.10:8080/inform`

adopted the client, but i again see this stun issue
![image](https://user-images.githubusercontent.com/136934/35239427-b9e6e06c-ffb0-11e7-8d42-335161333a07.png)

But well it cannot be by design running that every since container start right?

So setting the inform URL fixes it until the next restart apperently

**Comment by rogierlommers** [comment]
Not what I meant. Go to settings, controller settings and look for the item "controller hostname/ip". Point the (internal) ip address + port from your router. Since you are running the controller inside a docker container, it get's the internal Docker subnet assigned. You should override it, so the devices can also easily point to it.

**Comment by dam09fr** [comment]
![](http://nsa39.casimages.com/img/2018/01/23/180123025347421175.jpg)
I'm not sure about the need to check the "Override" option.

**Comment by rogierlommers** [comment]
I have this:

<img width="647" alt="screen shot 2018-01-23 at 15 02 34" src="https://user-images.githubusercontent.com/3907131/35279808-79a8201c-004e-11e8-9f96-798f6f7a8ce8.png">

**Comment by EugenMayer** [comment]
Thank you guys, setting the controller hostname fixed it for me. Sorry for bothering you on this, should have thought about that. I am just very new to the whole unifi thing and not entirely aware how it works - but yeah, the way the APs register using a push system, it must understand its external IP.

Cant we make this a general variable somehow ( i guess not ) because that issue is going to be a thing for every docker unifi persons, isnt it?

**Comment by rogierlommers** [comment]
No problem, glad I could help.
