### ISSUE TITLE
How to add own Certificate 

### ISSUE THREAD

**Issue by ning42** [linuxserver/docker-unifi#46]
I was wondering if there is a way to use a own certificate somehow?
I'm running the container on a QNAP, where there all-ready is a Let's encrypt certificate

**Comment by thelamer** [comment]
Unifi uses a different cert format it is java keystore, you can see the generation logic here: 

https://github.com/linuxserver/docker-unifi/blob/master/root/etc/cont-init.d/30-keygen

The keystore file is in your /config/data directory for replacement. 

Here is the logic for converting a standard cert to a java keystore file: 

https://community.letsencrypt.org/t/importing-letsencrypt-into-java-and-glassfish/9711

Once you have a keystore file you can just swap out the file and restart the container, as far as automating this every 90 days on expiration that would need to be a custom implementation.

**Comment by sparklyballs** [comment]
this involves a lot of manual intervention or third party scripts 
best bet is to try and follow the links @thelamer provided

but this isn't something we support
