### ISSUE TITLE
Support 5.7.x stable release

### ISSUE THREAD

**Issue by kavehv** [linuxserver/docker-unifi#48]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by dam09fr** [comment]
Two versions have been released yesterday:
 - [UniFi 5.6.36 LTS Stable](https://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-5-6-36-LTS-Stable-has-been-released/ba-p/2277323)
 - [UniFi 5.7.20 Stable](https://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-5-7-20-Stable-has-been-released/ba-p/2271529)
Notice that none of this releases is available to the products downloads pages.

As it is the 1st release of 5.7.x I suggest to add a "LTS" tag (in GitHub and Docker Hub) to continue support the 5.6.x branch for now, and push 5.7.x to stable.

**Comment by sparklyballs** [comment]
neither have been released

we only build a version when it hits the downloads page because unifi have an awful track record on pulling builds that have been "released" on blog posts and we have been caught out 3 times before

**Comment by dam09fr** [comment]
@sparklyballs Even if both are not in the download page, can you please tell us if you are OK with the idea of setting-up a "LTS" branch for 5.6.x and moving stable to 5.7.x (in Github and DockerHub) ?

**Comment by kavehv** [comment]
@sparklyballs I'm a little surprised this was closed so promptly.  5.7.x has been moved to stable and is available to download.  Is there a reason this project should be resistant to taking it?

**Comment by sparklyballs** [comment]
@kavehv we are not resistant but at the time this was posted the release was NOT on the download page (which is our criteria for a release given unifi's not so stellar track record of pulling releases)

and we have in fact just made a release branch for 5.7x

**Comment by kavehv** [comment]
@sparklyballs ah, most excellent.  Will this be made available through a tag on dockerhub?  It would be nice if the dockerhub maintained 5.6.x and 5.7.x tags.  The other repo that maintains a unifi image does this (I think it's jacobalberty/unifi).  In general, the way tags are laid out in that repo are more inline with what I've experience on dockerhub.

**Comment by Kwull** [comment]
Currently, 5.7.20 IS on the download page - https://www.ubnt.com/download/unifi/unifi-ap-ac-pro/uap-ac-pro/unifi-5630-controller-debianubuntu-linux 

Can you please make the stable release of 5.7.20?

**Comment by dam09fr** [comment]
@Kwull There is an "unstable" tag on DockerHub for this 5.7.20 release !
https://hub.docker.com/r/linuxserver/unifi/

**Comment by rogierlommers** [comment]
But according to unifi, it's not unstable, right?

**Comment by sparklyballs** [comment]
according to us it is though

the 2 members of our team that have tried it so far have had issues with AP's stuck in an adopting loop and there are threads on the unifi forum with users reporting the same issue 

so it is tagged unstable regardless of what unifi might call it

**Comment by Kwull** [comment]
@sparklyballs thanks a lot for the clarification! Now it makes sense.
