### ISSUE TITLE
Update repository line in Dockerfile to latest stable version

### ISSUE THREAD

**Issue by rubylaser** [linuxserver/docker-unifi#6]
Hello the Unifi developers decided to change their repository again.  Could you update this line from the Dockerfile to point to the new stable repo?

``` bash
RUN echo "deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti" >> /etc/apt/sources.list && \
```

to this...
``` bash
RUN echo "deb http://www.unnt.com/downloads/unifi/debian unifi5 ubiquiti" >> /etc/apt/sources.list && \
```

**Comment by IronicBadger** [comment]
Yes, we could. Or... you could submit a pull request!! :)

**Comment by rubylaser** [comment]
Somebody already did that for me on June 1st. :)

https://github.com/linuxserver/docker-unifi/pull/4

**Comment by sparklyballs** [comment]
latest rebase/rewrite is using the newer repo

**Comment by rubylaser** [comment]
Thanks!  I just updated and it's working great :+1:
