### ISSUE TITLE
Expose internal server logs to container stdout

### ISSUE THREAD

**Issue by Gunni** [linuxserver/docker-unifi#63]
We have been getting random issues where the container is running but resulting in 500 server errors, since the server is in active use I have not had the chance to debug the issue live, but i did check the logs and they are completely useless.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
CentOS 7

	/usr/bin/docker run --name %n \
	        --net=host \
	        -v /opt/unifi:/config:Z \
	        -e PUID=1001 \
	        -e PGID=1001 \
	        linuxserver/unifi:125

	[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
	[s6-init] ensuring user provided files have correct perms...exited 0.
	[fix-attrs.d] applying ownership & permissions fixes...
	[fix-attrs.d] done.
	[cont-init.d] executing container initialization scripts...
	[cont-init.d] 10-adduser: executing...
	-------------------------------------
		  _         ()
		 | |  ___   _    __
		 | | / __| | |  /  \
		 | | \__ \ | | | () |
		 |_| |___/ |_|  \__/
	Brought to you by linuxserver.io
	We gratefully accept donations at:
	https://www.linuxserver.io/donations/
	-------------------------------------
	GID/UID
	-------------------------------------
	User uid:    1001
	User gid:    1001
	-------------------------------------
	[cont-init.d] 10-adduser: exited 0.
	[cont-init.d] 20-config: executing...
	[cont-init.d] 20-config: exited 0.
	[cont-init.d] 30-keygen: executing...
	[cont-init.d] 30-keygen: exited 0.
	[cont-init.d] done.
	[services.d] starting services
	[services.d] done.

tail -f the logs to container stdout should work right? I was considering making a watchdog with `curl --head -kfs https://localhost:8443/ > /dev/null` and if exit code is not 0, restart it. But i decided to come ask here first since that feels hacky.

**Comment by sparklyballs** [comment]
the logs are in /config/logs

no need to pollute the docker log with pages and pages of noise when they are in the volume mount.
