### ISSUE TITLE
New versions published on downloads page

### ISSUE THREAD

**Issue by Gophlin** [linuxserver/docker-unifi#68]
It seems Ubiquiti had updated it's download page to reference 5.8.24 and 5.6.39 LTS. 
https://www.ubnt.com/download/unifi/

Could we see this reflected in the docker container?

**Comment by sparklyballs** [comment]
what like this ?

https://github.com/linuxserver/docker-unifi/blob/unstable/Dockerfile#L10

and this ?

https://github.com/linuxserver/docker-unifi/blob/master/Dockerfile#L10

**Comment by Gophlin** [comment]
Not quite (or i'm misunderstanding). They've updated all documentation to indicate that 5.8 is now the stable branch: https://help.ubnt.com/hc/en-us/articles/115000441548-UniFi-Current-Controller-Versions so i would think that should be the default

**Comment by sparklyballs** [comment]
we call anything other than LTS unstable regardless of what ubnt might label it
