### ISSUE TITLE
Update image tags to match Ubiquiti ones

### ISSUE THREAD

**Issue by web2wire** [linuxserver/docker-unifi#71]
This is a good and useful docker image. However currently there are really only two tags, 'latest' which corresponds to 5.6.x and 'unstable' which the documentation suggests is 5.7.x but I believe it's actually 5.8.x.

This is slightly confusing as if you read this page [this page](https://community.ubnt.com/t5/UniFi-Wireless/UniFi-Controller-Releases-Updated-Jun-27th-2018/td-p/2371605) on the Ubiquiti support forum they name their branches differently.

Have you considered using these tags on the docker image as well? E.g. 5.6.x would be 'stable-lts' or just 'lts', 5.8.x would be 'stable' and 5.9.x would be 'testing' (if you decide to support that branch also). This would make it easier to correlate the images with the Ubiquiti branches. Adding version specific tags (e.g. 5.6, 5.8, 5.9) as well would also help to make it clear what is what.

Finally, 5.6 is apparently only supported until November 2018 anyway so the current 'latest' tag would not be supported after that and the current 'unstable' tag would be the 'stable' one. Updating/adding new tags before this time may help to make migration easier once 5.6 drops off the picture.

**Comment by web2wire** [comment]
Just noticed that there has been some discussion on this before (could have sworn I looked first, but probably a different repo). Feel free to close this or limit to a discussion of what will happen from November? Assuming Ubiquiti move 5.8 to LTS once 5.6 goes unsupported will your 'latest' tag follow this?

**Comment by aptalca** [comment]
Our tags will reflect what we deem stable / unstable

**Comment by web2wire** [comment]
Thanks for the quick reply. I need something a little more predictable and less arbitrary than that at this time so will have to use another image for now.
