### ISSUE TITLE
5.8 is no longer unstable branch. 

### ISSUE THREAD

**Issue by meauses** [linuxserver/docker-unifi#72]
The 5.8 version should no longer be considered unstable branch. its been stable since a short while now.

**Comment by sparklyballs** [comment]
It’s merely a name, we could call it Ralph and it would still be the 5.8 branch.

**Comment by meauses** [comment]
sure, but why not bring it in line with the branch names of unifi itsself? would offer the possibility to use the new unstable branch when thats been identified. 
https://help.ubnt.com/hc/en-us/articles/115000441548-UniFi-Current-Controller-Versions

**Comment by sparklyballs** [comment]
currently we have no plans to use unifi's unstable branch, enough issues in the past with their allegedly  "stable" releases.
