### ISSUE TITLE
New Docker Repo - Unifi Video Service - How to ?

### ISSUE THREAD

**Issue by timpur** [linuxserver/docker-unifi#73]
How to best go about creating a new docker image Repo for unifi video service ?

https://www.ubnt.com/download/unifi-video/

**Comment by sparklyballs** [comment]
depends what you're actually asking for.

if you're looking for us to build something, not sure anyone on the team has a unifi video device to test with. 

or , if you've created a docker image and want us to host it....

**Comment by H2OKing89** [comment]
It would be awesome if linuxserver could build one!

**Comment by timpur** [comment]
@sparklyballs, which one is more likely to happen :P

**Comment by CHBMB** [comment]
Well, basically, we're not going to make on as we have no ability to test it.

**Comment by Kwull** [comment]
I'm using pducharme/unifi-video-controller - so far so good

**Comment by timpur** [comment]
okay thanks @CHBMB, im the same situation so cant talk ...
