### ISSUE TITLE
improve documentation on how to configure the controller ip

### ISSUE THREAD

**Issue by rburgst** [linuxserver/docker-unifi#74]
The documentation does not really specify whether or how the unifi controller is to be configured.

I had intermittent problem that my UAP AC LR was stuck in adopting state. After I reboot it, it then works for a while again.
I configured rsyslog and found many errors in the log such as 

```
ace_reporter.reporter_fail(): initial contact failed #4, url=http://172.17.0.3:8080/inform, rc=11
```

The address 172.17.0.3 is the internal docker ip. It seems like the UAP tried to connect to the controller via the internal docker ip.

I think I managed to fix this by overriding the unifi controller adress from within the controller configuration.

The configuration option is `override inform host with controller hostname/IP`.

* Host OS : Synology DS718+ (Intel linux, docker)
* Docker container version: linuxserver/unifi:unstable

**Comment by j0nnymoe** [comment]
We do state about the the adopting settings here: https://github.com/linuxserver/docker-unifi#setting-up-the-application

**Comment by rburgst** [comment]
Thats what I had previously and I constantly had problems where after a while the device was hanging in adopting state. I specifically had to check the "Override inform host with controller" checkbox to make it work.

**Comment by j0nnymoe** [comment]
Just had a thought, are you using host or bridge networking?

**Comment by rburgst** [comment]
Using bridge networking

**Comment by j0nnymoe** [comment]
Ok, that actually makes sense and also explains why I might've had a problem when switching from host to bridge... I'll look into adding some bits to the readme's.
