### ISSUE TITLE
5.6.40 released

### ISSUE THREAD

**Issue by CyberMew** [linuxserver/docker-unifi#75]
https://community.ubnt.com/t5/UniFi-Routing-Switching/UniFi-SDN-Controller-5-6-40-LTS-Stable-has-been-released/td-p/2488207

Will we see an update this week? (I'm using nanoHD and one of the fixes affects me too)

**Comment by sparklyballs** [comment]
not until it hits this page https://www.ubnt.com/download/unifi do we class an update as such.

**Comment by CyberMew** [comment]
Thanks! Looks like we will be having an update to the image soon.
