### ISSUE TITLE
Move stable to 5.9.29

### ISSUE THREAD

**Issue by GlenHertz** [linuxserver/docker-unifi#82]
Please upgrade the stable branch to match the latest stable from Ubiquiti: version [5.9.29](https://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-SDN-Controller-5-9-29-Stable-has-been-released/ba-p/2516852).

**Comment by j0nnymoe** [comment]
Right now our stable branch follows the LTS branch of unifi and our unstable branch will follow latest which is already at 5.9.29.
