### ISSUE TITLE
Add 5.10 branch/tag for people not wanting to move from 5.9 to 5.10

### ISSUE THREAD

**Issue by cwhits** [linuxserver/docker-unifi#87]
I swear I'm not beating a dead horse and reviving the whole `unstable` vs `stable` debate but 5.10 was released today and "the required minimum firmware for UAP/USW will be 4.0.9 and for USG will be 4.4.34". People might not be keen on going to 5.10 right away. Perhaps adding another tag for that branch moving forward (since it was just released today and would be a "fresh" start)?

**Comment by aptalca** [comment]
We are just about to migrate this image to a new builder which will tag images with the software version so you can pull specific versions or stay on specific branches.

**Comment by rburgst** [comment]
@aptalca when can we expect the new builder?

**Comment by aptalca** [comment]
When it's ready

**Comment by rburgst** [comment]
Is there a github issue I can track so I can watch its notifications?

**Comment by aptalca** [comment]
Testing only for now ;)
https://github.com/linuxserver/docker-unifi-controller
