### ISSUE TITLE
xenial rebase: custom bootscript and autoupdate?

### ISSUE THREAD

**Issue by AndreasA** [linuxserver/docker-unifi#9]
Just wanting to know if the current xenial rebase supports auto update and custom boot script 
because those features were part of the  linuxserver/baseimage and I don't think they are part of the default ubuntu/xenial image, are they?

Or will those be re-added with this merge request https://github.com/linuxserver/docker-unifi/pull/8 ?

**Comment by sparklyballs** [comment]
There are no plans to readd autoupdating, it caused more issues with containers than almost anything else.

**Comment by AndreasA** [comment]
What abou the Custom script? That way one could optionally add or disable a script which does the updating when one wants to

**Comment by sparklyballs** [comment]
there is currently no plans to bring back autoupdates or allow custom scripting to acheieve it.

and does this container really warrant it ? 
it's not something that is updated that often.
