### ISSUE TITLE
Unstable should move to 5.10.17

### ISSUE THREAD

**Issue by lvlie** [linuxserver/docker-unifi#91]
New stable release (non-LTS) is the 5.10 branch. As this repository tracks the non-LTS stable as unstable, the unstable should be moved to the 5.10 branch, of which 5.10.17 is the newest.

I'll be happy to test the image.

Edit: checked the jenkins vars and the custom version command in the pipeline-unstable branch beautifully returns 5.10.17. Just starting a new build should suffice

Thanks :-)

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by aptalca** [comment]
There is a new development on the way, hold tight
