### ISSUE TITLE
Remove duplicate repo for Unifi

### ISSUE THREAD

**Issue by lvlie** [linuxserver/docker-unifi#92]
Just found https://github.com/linuxserver/docker-unifi-controller, which seems to be updated to the latest stable release, were this one is not. Maybe this one should redirect to the other? Or is there a valid reason to have 2?

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by aptalca** [comment]
The other one is in testing, not released yet
